version: "3"
services:
  server:
    container_name: server
    build:
      context: ./server
    depends_on:
      - db
    volumes:
      - ./server:/usr/app
      - /usr/app/node_modules
    environment:
      - DBURI=mongodb://db:27017/ulang
      - PORT=80
      - NODE_ENV=production
    ports: ['80:80']

  db:
    container_name: db
    image: mongo:4.0
    restart: always

  client:
    container_name: client
    build:
      context: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=production
      - SERVER_URL=http://localhost/
